name: weeddetectapp
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  tflite_flutter: ^0.11.0
  image: ^4.5.3
  image_picker: ^1.1.2
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tflite_model.tflite
    - assets/label_map.json
  
    - assets/topography.png

    - assets/10weed_model.tflite
    - assets/label_maptry.json

    - assets/10weed_model_pt1.tflite
    - assets/label_maptry1.json

    - assets/10weed_model_pt3.tflite
    - assets/label_maptry3.json
    
    - assets/10weedwithpipelinetrial4.tflite
    - assets/label_maptry4.json

    - assets/images/dev1.png
    - assets/images/dev2.png
    - assets/images/dev3.png

    
  fonts:
    - family: Causten
      fonts:
        - asset: assets/fonts/Causten-Regular.otf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

